import { Metadata } from "next";
import { RiProfileLine } from "react-icons/ri";

export const metadata: Metadata = {
  title: "Profile",
  description: "Generated by create next app",
};

export default function ProfileLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div>
      <main className="bg-gradient-to-b from-gray-900 to-gray-800">
        <div className="flex justify-center items-center gap-8">
          <h1 className="text-center text-white pt-4 font-bold sm:text-2xl md:text-3xl">
            Profile
          </h1>
          <div>
            <RiProfileLine className="text-yellow-600 text-5xl" />
          </div>
        </div>
        {children}
      </main>
    </div>
  );
}
