import NavBar from "@/components/dashboard/components/navBar/NavBar";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="overflow-auto scrollbar-hide">
      <main>
        <NavBar />
        {children}
      </main>
    </div>
  );
}
